### PR TITLE
don't break when there are few or collinear points

### PR DESCRIPTION
**Pull request by Fil**
fixes https://github.com/d3/d3-delaunay/issues/19 and https://github.com/d3/d3-delaunay/issues/20
~~gross (try/catch)~~

~~this is not ready to merge: there are issues with (at least):~~
- ~~naming (this `.__` property is a placeholder)~~
- ~~tuning the value of `g` (1e9 works in the examples but creates some instability, as evidenced by the fact that lines are not neat — with 1e8 they are perfectly in the middle).~~
- ~~should the API allow to request a strict Delaunay — or on the contrary, offer this "robust" approach as an option?~~

### CODE REVIEW

**Comment by Fil** [comment]
Rebased (with some clean-ups) on the indexHull branch.

**Comment by mourner** [comment]
Personally this looks too hacky to be worth the benefit in this form... Can we approach the issue some other way, including changes to Delaunator upstream? The "try/catch" just feels like a blanket cover fix, and depending on a constant number to designate "far away" doesn't feel right too — e.g. I can easily imagine Delaunay being fed some big numbers in this range.

**Comment by Fil** [comment]
Agreed. In d3-geo-voronoi in particular, the numbers can be very large after the stereographic projection — and there is already too much numeric instability (see https://github.com/Fil/d3-geo-voronoi/issues/10).

I wonder if the solution wouldn't be to return an empty `triangles`, and a `hull` consisting of the non-duplicate points, ordered along an arbitrary vector (for instance the normal to the two first non identical points, if there are >= 2 of them).

With this approach Delaunator would not lie about triangles ("here's your 0 triangles"), and just a little bit about the hull. d3-delaunay could work with that pseudo-hull and create the list of infinite cells in that order.

**Comment by Fil** [comment]
New code, much cleaner. Updated the tests at https://observablehq.com/d/5e4da35146afd543.
I'll need to rebase and clean the whole thing, but that will be later.

Needs this change to Delaunator: https://github.com/Fil/delaunator/commit/b96802021867a788c2c2111085562a086996b52c

**Comment by Fil** [comment]
Superseded by #64.

**Pull request closed without merging**
