### PR TITLE
delaunay.find and coincident points

### PR DESCRIPTION
**Pull request by Fil**
fixes https://github.com/d3/d3-delaunay/issues/55

### CODE REVIEW

**Comment by Fil** [comment]
I thought of a list of visited nodes (to avoid those if we get to another dead-end), but then it costs memory… and too much code.

**Comment by mourner** [comment]
Not a perfect approach too, but perhaps a custom seeded random would work?

**Comment by Fil** [comment]
I think `(i + 1) % length` would be correct, in fact, in all cases… I had started with that, then I realised that I had to make 100% sure it would never fail.
But, there's no way the step ever goes from a normal point to a coincident point. So this call happens only when the initial hint *i* is coincident, and the only way it could loop forever, if we enumerate points with i => i+1, is if we had only coincident points — an impossibility. Right?

**Comment by Fil** [comment]
closing this branch in favor of a local d3 branch

**Pull request closed without merging**
