### PR TITLE
upgrade to delaunator@4

### PR DESCRIPTION
**Pull request by Fil**
fixes https://github.com/d3/d3-delaunay/issues/50

removes delaunay.outedges from the API, replaced with the private _hullIndex

### CODE REVIEW

**Comment by mourner** [comment]
@Fil let's merge then? Or did you plan to get the degenerate cases handling into the same major version?

**Comment by mourner** [comment]
@Fil that one is merged, but I'm thinking of also merging in https://github.com/mapbox/delaunator/pull/48 to cram this into a semver major too, and then we can release new major versions of both `Delaunator` and `d3-delaunay`.

**Comment by Fil** [comment]
Yes let's move forward

**Comment by Fil** [comment]
Superseded by https://github.com/d3/d3-delaunay/pull/64

**Pull request closed without merging**
